### ISSUE TITLE
Nvidia Jetson Nano 2GB Success

### ISSUE THREAD

**Issue by smumriak** [futurejones/swift-arm64#13]
Hey
I'm running swift from this build on my Jetson Nano 2GB successfully :) I did not run explicit tests, just built and ran my pet project. Literally worked out of the box

**Comment by futurejones** [comment]
Thats great to hear! 😁

**Comment by smumryak** [comment]
Yea, a side note, I'm running it on 20.04 with 4.9 kernel, but it's not officially supported by nvidia. Officially supported is still 18.04 with 4.9 kernel version and I skipped it as a whole. I'm also going to try to update to 20.10 and check it toolkit works on it. I mean it should, since the CPU is not much of a difference compared to RPi 3B+

**Comment by smumryak** [comment]
Ok, few tiny updates from my side: I could not make 20.10 work on jetson nano. So could not test swift installation there. I'm gonna use this ticked for various updates on my side. One thing I've found is that for some reason the swift dynamic libraries are not visible for applications that were compiled on other machine. What I did is added `/etc/ld.so.conf.d/swift.conf` with this:
```
/usr/lib/swift/linux
/usr/lib/swift_static
```
and ran `ldconfig`. I guess this could be added as part of deb package.
